### ISSUE TITLE
Source code 

### ISSUE THREAD

**Issue by stewartgill1977** [RealNobser/DomeLiftMechanism#1]
Hi is there any way i can get access to the full source code?. I have some mod gears that allow the servos to do a bigger sweep it works great but is now to fast between the pauses and id like to slow it down. I have downloads the zip file but it looks like most of the code is missing so when importing it to eclipse i cant do anything.

thanks

**Comment by RealNobser** [comment]
The dependencies are described in the platform.ini:

    https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library
    https://github.com/nRF24/RF24

It is not common to include them in the main project, too.
