### ISSUE TITLE
Opening of pie panels

### ISSUE THREAD

**Issue by stewartgill1977** [RealNobser/DomeLiftMechanism#2]
Hi i hope you can help the code works great but i have noticed that when the lift system sends a tool up its very very close to the pie open servo running if not at the same time. My tools are very close to the pies and im wounding if you can dell me where i can ad a small delay from when the door is opens to when the lift activates to go up to give a little time for the door to be open. I have the code in visual studio im not a programmer put just need to know where to put the delay command if possible :)

thanks for your help

**Comment by stewartgill1977** [comment]
Never mind i found it works great now with a slight delay of (600) right before the motor up command activates

**Comment by RealNobser** [comment]
Nevertheless maybe a good idea to add a feature like this in the upcoming renewed code.

**Comment by stewartgill1977** [comment]
Yes please not a bad idea. Also I'm not shore if the code already has this most like dose but a check to make shore the panel is open before it lifts so that it does not try to ram a closed door

**Comment by stewartgill1977** [comment]
Would also be great if when the lift was down the servos where off no signal or something to stop any buzzing due to the item putting a slight pressure on the servo. The cheap ones are the worse for this and will over heat them very fast Thanks again for you programing :)

**Comment by RealNobser** [comment]
> Yes please not a bad idea. Also I'm not shore if the code already has this most like dose but a check to make shore the panel is open before it lifts so that it does not try to ram a closed door

This is, what the "lock" mechanism is for.  The dome lift locks the panels, so no MarcDuino sequence can close it until it is unlocked (exception: Power loss)

**Comment by RealNobser** [comment]
> Would also be great if when the lift was down the servos where off no signal or something to stop any buzzing due to the item putting a slight pressure on the servo. The cheap ones are the worse for this and will over heat them very fast Thanks again for you programing :)

Dome lift servos or panel servos? Panel servos are switching off after 3 seconds.

**Comment by stewartgill1977** [comment]
Lift servos they are still on when down on idle. and some buzz if there is the slightest load on them .

**Comment by stewartgill1977** [comment]
ok thanks does that mean if the pie servo failed and stopped working and was closed would the lift still send the item up?

**Comment by stewartgill1977** [comment]
> > Yes please not a bad idea. Also I'm not shore if the code already has this most like dose but a check to make shore the panel is open before it lifts so that it does not try to ram a closed door
> 
> This is, what the "lock" mechanism is for. The dome lift locks the panels, so no MarcDuino sequence can close it until it is unlocked (exception: Power loss)

ok thanks does that mean if the pie servo failed and stopped working and was closed would the lift still send the item up?. If so i might invest in some better quality servos for the pies

**Comment by stewartgill1977** [comment]
> > Would also be great if when the lift was down the servos where off no signal or something to stop any buzzing due to the item putting a slight pressure on the servo. The cheap ones are the worse for this and will over heat them very fast Thanks again for you programing :)
> 
> Dome lift servos or panel servos? Panel servos are switching off after 3 seconds.

Lift servos they are still on when down on idle. and some buzz if there is the slightest load on them .

**Comment by RealNobser** [comment]
I will check all your suggestions. Just one hint: I'm just hosting the source code here on github, it is not my source. I will rewrite the dome lift code in the future to match our AstroCAN-Concept, but that will take a while.

**Comment by RealNobser** [comment]
> > > Yes please not a bad idea. Also I'm not shore if the code already has this most like dose but a check to make shore the panel is open before it lifts so that it does not try to ram a closed door
> > 
> > 
> > This is, what the "lock" mechanism is for. The dome lift locks the panels, so no MarcDuino sequence can close it until it is unlocked (exception: Power loss)
> 
> ok thanks does that mean if the pie servo failed and stopped working and was closed would the lift still send the item up?. If so i might invest in some better quality servos for the pies

Yes. The standard servos used here do not have any feedback capability. There is no way to find out, if the servo reached its position or not. Not here or anywhrere else. There are servos on the market, that are capable of that, too, but the will need a totally differen wiring, controller hardware and of course a totally different sketch.

**Comment by stewartgill1977** [comment]
ok thanks for all the info easier to just replace a servo if it goes bad they are cheap as chips :)

**Comment by RealNobser** [comment]
Buzzing is always bad. Try to adjust them mechanically, so they can move without collision. Maybe you have to adjust the end positions in the code.

**Comment by stewartgill1977** [comment]
thanks ill take a look at it
