### ISSUE TITLE
Periscope Lights connection

### ISSUE THREAD

**Issue by stewartgill1977** [RealNobser/DomeLiftMechanism#3]
HI iv been looking arounds to see how you wire up the Periscope to turn on when its activated but can not find any doc's would you know how to wire the lights up or know where to look. Im using bens Periscope  https://shop.printed-droid.com/produkt/periscope-light-kit/ and bens lift system https://shop.printed-droid.com/produkt/dome-lift-controller-matt-zwarts-system/ with your code :) i see the pins for the zapper light and the bad motivator lights with are working great just no Periscope lights.

**Comment by RealNobser** [comment]
Hi!

The code here is just the original Matt Zwarts code with additional I2C communication to control the MarcDuino Panels. As far as I can see, it does not support light control. I'll talk to Ben how to realize that.

**Comment by RealNobser** [comment]
Unfortunately in the original code there is no pin specified for periscope lights. Possible workaround: install a second top endstop that triggers the power for the periscope light. So it will switch on the periscope as soon as it reaches the top position and switches it off, when moving down.
